# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-07-11 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_auto_20180711_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.FileField(upload_to='app/curso/documents/'),
        ),
    ]
