# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-07-11 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_auto_20180711_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.FileField(upload_to=''),
        ),
    ]
