# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-30 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='computadora',
            field=models.TextField(blank=True),
        ),
    ]
