# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-07-06 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_auto_20180630_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='computadora',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
